# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WeAppExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'SSZipArchive', '~> 2.2.2'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'Masonry', '~> 1.0.0'
  pod 'YYKit', '~> 1.0.9'
  
end
